/*
 * Copyright 2026 The RuleGo Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package eipclient wraps danomagnum/gologix, providing Rockwell ControlLogix/
// CompactLogix PLC connections via EtherNet/IP (CIP) and bulk tag read/write.
//
// Only supports CIP devices (ControlLogix/CompactLogix/Micro820), not PLC5/SLC/MicroLogix(PCCC).
// Points must specify type.

package eipclient

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/danomagnum/gologix"
	"github.com/rulego/rulego-components-iot/pkg/iot_points"
	"github.com/rulego/rulego/api/types"
)

// EipDataMsgType is the EIP data message type.
const EipDataMsgType = "EIP_DATA"

// Data is the unified point output contract.
type Data struct {
	Name      string      `json:"name"`
	Address   string      `json:"address"` // tag name
	Value     interface{} `json:"value"`
	Type      string      `json:"type"`
	Quality   string      `json:"quality"`
	Timestamp time.Time   `json:"timestamp"`
}

// Point EIP point definition, shared for read/write
type Point struct {
	Name  string `json:"name"`            // Point name
	Tag   string `json:"tag"`             // Symbolic tag name, e.g. MyDB.Temperature
	Type  string `json:"type"`            // BOOL/INT/DINT/REAL/STRING/...
	Value string `json:"value,omitempty"` // Write only: string representation of value
}

// ConfigProp EIP connection configuration interface
type ConfigProp interface {
	GetServer() string // host or host:port, default port 44818
	GetSlot() int      // CPU slot, auto-generates CIP path
	GetPath() string   // Optional: manually override CIP path, e.g. 1,0
	GetTimeout() int   // seconds
}

// Holder EIP client configuration holder
type Holder struct {
	Config ConfigProp
}

// DefaultHolder default configuration
func DefaultHolder(c ConfigProp) *Holder {
	return &Holder{Config: c}
}

// NewClient creates and connects a gologix client.
func (h *Holder) NewClient() (*gologix.Client, error) {
	if h.Config == nil {
		return nil, errors.New("eip config is nil")
	}
	host, port, err := iot_points.ParseServer(h.Config.GetServer(), 44818)
	if err != nil {
		return nil, err
	}
	client := gologix.NewClient(host)
	client.Controller.Port = uint(port)
	// CIP path priority: configured path > auto-generated by slot
	if path := strings.TrimSpace(h.Config.GetPath()); path != "" {
		p, err := gologix.ParsePath(path)
		if err != nil {
			return nil, fmt.Errorf("parse path %q error: %w", path, err)
		}
		client.Controller.Path = p
	} else {
		slot := h.Config.GetSlot()
		p, err := gologix.ParsePath(fmt.Sprintf("1,%d", slot))
		if err != nil {
			return nil, fmt.Errorf("auto slot path \"1,%d\": %w", slot, err)
		}
		client.Controller.Path = p
	}
	if t := h.Config.GetTimeout(); t > 0 {
		client.SocketTimeout = time.Duration(t) * time.Second
	}
	if err := client.Connect(); err != nil {
		return nil, err
	}
	return client, nil
}

// ReadPoints batch reads tags. Single tag failure does not affect others (marked quality=bad)
func ReadPoints(client *gologix.Client, points []Point, logger types.Logger) ([]Data, error) {
	if client == nil {
		return nil, errors.New("eip client is nil")
	}
	results := make([]Data, 0, len(points))
	failCount := 0
	var lastErr error
	for _, p := range points {
		d := Data{
			Name:      p.Name,
			Address:   p.Tag,
			Type:      strings.ToUpper(strings.TrimSpace(p.Type)),
			Timestamp: time.Now(),
		}
		val, err := readTag(client, p.Tag, p.Type)
		if err != nil {
			d.Quality = "bad"
			failCount++
			lastErr = err
			if logger != nil {
				logger.Errorf("[EIP] read %s error: %v", p.Tag, err)
			}
		} else {
			d.Quality = "good"
			d.Value = val
		}
		results = append(results, d)
	}
	// All points failed: suspected connection-level error, return error
	if len(points) > 0 && failCount == len(points) {
		return results, fmt.Errorf("all %d points failed (possible connection error): %w", failCount, lastErr)
	}
	return results, nil
}

// readTag reads single tag by type into corresponding type pointer
func readTag(client *gologix.Client, tag, typ string) (interface{}, error) {
	switch strings.ToUpper(strings.TrimSpace(typ)) {
	case "BOOL":
		var v bool
		err := client.Read(tag, &v)
		return v, err
	case "BYTE", "SINT", "USINT":
		var v byte
		err := client.Read(tag, &v)
		return v, err
	case "INT", "INT16":
		var v int16
		err := client.Read(tag, &v)
		return v, err
	case "UINT", "WORD", "UINT16":
		var v uint16
		err := client.Read(tag, &v)
		return v, err
	case "DINT", "INT32":
		var v int32
		err := client.Read(tag, &v)
		return v, err
	case "UDINT", "DWORD", "UINT32":
		var v uint32
		err := client.Read(tag, &v)
		return v, err
	case "LINT", "INT64":
		var v int64
		err := client.Read(tag, &v)
		return v, err
	case "ULINT", "UINT64":
		var v uint64
		err := client.Read(tag, &v)
		return v, err
	case "REAL", "FLOAT":
		var v float32
		err := client.Read(tag, &v)
		return v, err
	case "LREAL", "DOUBLE":
		var v float64
		err := client.Read(tag, &v)
		return v, err
	case "STRING":
		var v string
		err := client.Read(tag, &v)
		return v, err
	}
	return nil, fmt.Errorf("unsupported eip type: %q (supported: BOOL/INT/DINT/REAL/STRING/...)", typ)
}

// WritePoints batch writes tags. Returns error immediately on any failure
func WritePoints(client *gologix.Client, points []Point) error {
	if client == nil {
		return errors.New("eip client is nil")
	}
	for _, p := range points {
		val, err := encodeValue(p.Value, p.Type)
		if err != nil {
			return fmt.Errorf("encode %s error: %w", p.Tag, err)
		}
		if err := client.Write(p.Tag, val); err != nil {
			return fmt.Errorf("write %s error: %w", p.Tag, err)
		}
	}
	return nil
}

// encodeValue parses value string by type into Go value (for Write)
func encodeValue(value, typ string) (interface{}, error) {
	v := strings.TrimSpace(value)
	switch strings.ToUpper(strings.TrimSpace(typ)) {
	case "BOOL":
		return parseBoolValue(v)
	case "BYTE", "SINT", "USINT":
		n, err := strconv.ParseUint(v, 0, 8)
		return byte(n), err
	case "INT", "INT16":
		n, err := strconv.ParseInt(v, 0, 16)
		return int16(n), err
	case "UINT", "WORD", "UINT16":
		n, err := strconv.ParseUint(v, 0, 16)
		return uint16(n), err
	case "DINT", "INT32":
		n, err := strconv.ParseInt(v, 0, 32)
		return int32(n), err
	case "UDINT", "DWORD", "UINT32":
		n, err := strconv.ParseUint(v, 0, 32)
		return uint32(n), err
	case "LINT", "INT64":
		n, err := strconv.ParseInt(v, 0, 64)
		return int64(n), err
	case "ULINT", "UINT64":
		n, err := strconv.ParseUint(v, 0, 64)
		return uint64(n), err
	case "REAL", "FLOAT":
		n, err := strconv.ParseFloat(v, 32)
		return float32(n), err
	case "LREAL", "DOUBLE":
		n, err := strconv.ParseFloat(v, 64)
		return n, err
	case "STRING":
		return v, nil
	}
	return nil, fmt.Errorf("unsupported eip type: %q", typ)
}

// parseBoolValue parses bool value string (supports true/false/0/1)
func parseBoolValue(s string) (bool, error) {
	s = strings.TrimSpace(s)
	if b, err := strconv.ParseBool(s); err == nil {
		return b, nil
	}
	if n, err := strconv.Atoi(s); err == nil {
		return n != 0, nil
	}
	return false, fmt.Errorf("invalid bool value: %q", s)
}
